"""Build dashboard/data.js from the canonical JSON files.

The dashboard reads `window.dashboardData` (defined in the generated file)
rather than fetching the JSON files at load time. This lets it work directly
from a file:// URL — double-click index.html and it loads — without needing
a local web server.

Run this manually whenever the JSON files change. The daily update script
also calls `build()` directly as its final step so the dashboard always
reflects the latest evaluation.

If a snapshot exists for today, the alerts it fired are baked into the
dashboard. Otherwise the alerts panel is empty (manual rebuild after an
edit, no fresh evaluation yet).

    python scripts/build_dashboard_data.py
"""

from __future__ import annotations

import json
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Optional

# Make sibling modules importable when run as a script.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from data_model import (
    REPO_ROOT,
    SNAPSHOTS_DIR,
    OpenPosition,
    load_portfolio,
    load_open_positions,
    load_closed_positions,
)

OUTPUT_PATH = REPO_ROOT / "dashboard" / "data.js"


def _load_latest_snapshot_alerts() -> list:
    """Return the alerts_fired from the most recent snapshot, or []."""
    if not SNAPSHOTS_DIR.exists():
        return []
    snapshots = sorted(SNAPSHOTS_DIR.glob("*.json"))
    if not snapshots:
        return []
    try:
        latest = json.loads(snapshots[-1].read_text(encoding="utf-8"))
        return latest.get("alerts_fired", [])
    except Exception:
        return []


def build(
    alerts=None,
    positions=None,
):
    """Produce the dashboard payload and write data.js.

    If `positions` is provided (typically by daily_update.py with enriched
    market data and canonical sector names), those are used. Otherwise the
    positions are reloaded from disk.

    If `alerts` is provided (typically by daily_update.py with the alerts it
    just fired), those are baked in. Otherwise the most-recent snapshot's
    alerts are used. If no snapshot exists, alerts are empty.
    """
    portfolio = load_portfolio()
    if positions is None:
        positions = load_open_positions().positions
    closed_positions = load_closed_positions()

    if alerts is None:
        alerts = _load_latest_snapshot_alerts()

    payload = {
        "portfolio": portfolio.model_dump(mode="json"),
        "positions_open": [p.model_dump(mode="json") for p in positions],
        "positions_closed": [p.model_dump(mode="json") for p in closed_positions.positions],
        "alerts": alerts,
        "built_at": datetime.now().isoformat(timespec="seconds"),
    }

    js = (
        "// Generated by scripts/build_dashboard_data.py - do not edit by hand.\n"
        "// Regenerate after any position or portfolio change.\n"
        f"window.dashboardData = {json.dumps(payload, indent=2, default=str)};\n"
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(js, encoding="utf-8")
    return payload


def main():
    payload = build()
    rel = OUTPUT_PATH.relative_to(REPO_ROOT)
    n_open = len(payload["positions_open"])
    n_closed = len(payload["positions_closed"])
    n_alerts = len(payload["alerts"])
    print(f"Wrote {rel}")
    print(
        f"  portfolio: {payload['portfolio']['account_name']} "
        f"({payload['portfolio']['market_regime']})  "
        f"open: {n_open}  closed: {n_closed}  alerts: {n_alerts}"
    )


if __name__ == "__main__":
    main()
