"""Build dashboard/data.js from the canonical JSON files.

The dashboard reads `window.dashboardData` (defined in the generated file)
rather than fetching the JSON files at load time. This lets it work directly
from a file:// URL — double-click index.html and it loads — without needing
a local web server.

Run this manually whenever the JSON files change. In Phase 2, the daily
update script calls this as its final step so the dashboard is always fresh.

    python scripts/build_dashboard_data.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

# Make sibling modules importable when run as a script.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from data_model import (
    REPO_ROOT,
    load_portfolio,
    load_open_positions,
    load_closed_positions,
)

OUTPUT_PATH = REPO_ROOT / "dashboard" / "data.js"


def main() -> None:
    # Validate as we load — pydantic catches malformed data here, not in the browser.
    portfolio = load_portfolio()
    open_positions = load_open_positions()
    closed_positions = load_closed_positions()

    payload = {
        "portfolio": portfolio.model_dump(mode="json"),
        "positions_open": [p.model_dump(mode="json") for p in open_positions.positions],
        "positions_closed": [p.model_dump(mode="json") for p in closed_positions.positions],
        "alerts": [],  # Phase 2 will populate this from alerts_history
        "built_at": datetime.now().isoformat(timespec="seconds"),
    }

    js = (
        "// Generated by scripts/build_dashboard_data.py — do not edit by hand.\n"
        "// Regenerate after any position or portfolio change.\n"
        f"window.dashboardData = {json.dumps(payload, indent=2)};\n"
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(js, encoding="utf-8")

    rel = OUTPUT_PATH.relative_to(REPO_ROOT)
    n_open = len(payload["positions_open"])
    n_closed = len(payload["positions_closed"])
    print(f"Wrote {rel}")
    print(
        f"  portfolio: {portfolio.account_name} ({portfolio.market_regime.value})  "
        f"open: {n_open}  closed: {n_closed}"
    )


if __name__ == "__main__":
    main()
